image: Visual Studio 2017

version: 0.1.{build}

environment:
  NASM_PREFIX: C:\Program Files\NASM\
  EDK_TOOLS_BIN: C:\projects\edk2-BaseTools-win32

install:
  # Clone submodules
  - git submodule init -q
  - git submodule update -q
  # Install Nasm
  - choco install nasm
  # Install ASL Compiler
  - curl -LO https://acpica.org/sites/acpica/files/iasl-win-20171215.zip
  - 7z e iasl-win-20171215.zip -oC:\ASL
  # Install edk2-BaseTools-win32
  - git clone -q https://github.com/tianocore/edk2-BaseTools-win32 C:\projects\edk2-BaseTools-win32
  - cd C:\projects\edk2-BaseTools-win32
  - git checkout -qf 0e088c19ab31fccd1d2f55d9e4fe0314b57c0097
  - cd C:\projects\updraft
  # Setup VS2015 environment variables
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64'

build_script:
  - nmake -f Makefile.win32 build
  - nmake -f Makefile.win32 build-ovmf

test: off
