image: Visual Studio 2017

version: 0.1.{build}

environment:
  NASM_PREFIX: C:\Program Files\NASM\
  EDK_TOOLS_BIN: C:\projects\edk2-BaseTools-win32

  matrix:
    # IA32 Build
    - ARCH: IA32
      BUILD_TARGET: DEBUG
      BUILD_TOOLS: VS2015
    - ARCH: IA32
      BUILD_TARGET: DEBUG
      BUILD_TOOLS: VS2015x86
    - ARCH: IA32
      BUILD_TARGET: RELEASE
      BUILD_TOOLS: VS2015
    - ARCH: IA32
      BUILD_TARGET: RELEASE
      BUILD_TOOLS: VS2015x86
    - ARCH: IA32
      BUILD_TARGET: NOOPT
      BUILD_TOOLS: VS2015
    - ARCH: IA32
      BUILD_TARGET: NOOPT
      BUILD_TOOLS: VS2015x86
    # X64 Build
    - ARCH: X64
      BUILD_TARGET: DEBUG
      BUILD_TOOLS: VS2015
    - ARCH: X64
      BUILD_TARGET: DEBUG
      BUILD_TOOLS: VS2015x86
    - ARCH: X64
      BUILD_TARGET: RELEASE
      BUILD_TOOLS: VS2015
    - ARCH: X64
      BUILD_TARGET: RELEASE
      BUILD_TOOLS: VS2015x86
    - ARCH: X64
      BUILD_TARGET: NOOPT
      BUILD_TOOLS: VS2015
    - ARCH: X64
      BUILD_TARGET: NOOPT
      BUILD_TOOLS: VS2015x86
    # ARM Build
    - ARCH: ARM
      BUILD_TARGET: DEBUG
      BUILD_TOOLS: VS2015
    - ARCH: ARM
      BUILD_TARGET: DEBUG
      BUILD_TOOLS: VS2015x86
    - ARCH: ARM
      BUILD_TARGET: RELEASE
      BUILD_TOOLS: VS2015
    - ARCH: ARM
      BUILD_TARGET: RELEASE
      BUILD_TOOLS: VS2015x86
    - ARCH: ARM
      BUILD_TARGET: NOOPT
      BUILD_TOOLS: VS2015
    - ARCH: ARM
      BUILD_TARGET: NOOPT
      BUILD_TOOLS: VS2015x86
    # AARCH64 Build
    - ARCH: AARCH64
      BUILD_TARGET: DEBUG
      BUILD_TOOLS: VS2015
    - ARCH: AARCH64
      BUILD_TARGET: DEBUG
      BUILD_TOOLS: VS2015x86
    - ARCH: AARCH64
      BUILD_TARGET: RELEASE
      BUILD_TOOLS: VS2015
    - ARCH: AARCH64
      BUILD_TARGET: RELEASE
      BUILD_TOOLS: VS2015x86
    - ARCH: AARCH64
      BUILD_TARGET: NOOPT
      BUILD_TOOLS: VS2015
    - ARCH: AARCH64
      BUILD_TARGET: NOOPT
      BUILD_TOOLS: VS2015x86

install:
  # Install Nasm
  - choco install nasm
  # Install ASL Compiler
  - ps: pushd C:\projects
  - ps: curl.exe -fsSLO https://acpica.org/sites/acpica/files/iasl-win-20171215.zip
  - ps: 7z x iasl-win-20171215.zip -oC:\ASL
  - ps: popd
  # Download edk2-BaseTools-win32
  - ps: pushd C:\projects
  - ps: curl.exe -fsSLO https://github.com/tianocore/edk2-BaseTools-win32/archive/0e088c19ab31fccd1d2f55d9e4fe0314b57c0097.zip
  - ps: 7z x 0e088c19ab31fccd1d2f55d9e4fe0314b57c0097.zip
  - ps: Rename-Item edk2-BaseTools-win32-0e088c19ab31fccd1d2f55d9e4fe0314b57c0097 edk2-BaseTools-win32
  - ps: popd
  # Download EDK II
  - ps: Remove-Item edk2
  - ps: curl.exe -fsSLO https://github.com/tianocore/edk2/archive/vUDK2017.zip
  - ps: 7z x vUDK2017.zip
  - ps: Rename-Item edk2-vUDK2017 edk2
  # Setup VS2015 environment variables
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64'

build_script:
  - nmake -f Makefile.win32 build
  - cd dist\image && 7z a ../../UpDraft.zip

artifacts:
  - path: UpDraft.zip

test: off
